"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Check, ChevronDown, Plus, Search, Trash2, X } from "lucide-react";
import { toast } from "sonner";
import type { Client, CRMGroup, Profile } from "@/app/types";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";

type AdditionalCost = { id: string; client_id: string; date_sent: string | null; people_id: string | null; cost: number | null; remarks: string; status: string; reason: string; courier: string; trip_id: string; items_sent: string; qty: string; verified: boolean | null; discussed: boolean | null; created_at: string };
type Props = { clients: Client[]; profiles: Profile[]; groups: CRMGroup[]; currentUserId?: string | null; currentUserRole?: string | null; clientAssignees: Record<string, string[]>; clientPmAssignees: Record<string, string[]> };
type Column = { key: string; label: string; width: number };
const initialColumns: Column[] = [
  { key: "project", label: "Project Name", width: 250 }, { key: "date_sent", label: "Date Sent", width: 142 }, { key: "people", label: "People", width: 150 }, { key: "cost", label: "Cost", width: 115 }, { key: "remarks", label: "Remarks", width: 260 }, { key: "status", label: "Status", width: 140 }, { key: "reason", label: "Reason", width: 155 }, { key: "courier", label: "Courier", width: 140 }, { key: "trip_id", label: "Trip ID", width: 145 }, { key: "items_sent", label: "Items Sent", width: 210 }, { key: "qty", label: "Qty", width: 95 }, { key: "created", label: "Date Created", width: 130 }, { key: "verified", label: "Verified?", width: 104 }, { key: "discussed", label: "Discussed?", width: 110 }, { key: "actions", label: "", width: 48 },
];
const cellClass = "h-10 min-w-0 bg-white px-2 text-sm text-slate-700 outline-none focus:bg-sky-50 focus:ring-1 focus:ring-inset focus:ring-sky-400";
const clientLabel = (client: Client) => `${client.name || "Unnamed client"}${client.displayId ? ` · ${client.displayId}` : ""}`;

export function AdditionalCostsBoard({ clients, profiles, groups, currentUserId, currentUserRole, clientAssignees, clientPmAssignees }: Props) {
  const [rows, setRows] = useState<AdditionalCost[]>([]);
  const [columns, setColumns] = useState(initialColumns);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const [pickerOpen, setPickerOpen] = useState(false); const [pickerQuery, setPickerQuery] = useState("");
  const [creatingFor, setCreatingFor] = useState<string | null>(null); const [deletingId, setDeletingId] = useState<string | null>(null); const [pendingDelete, setPendingDelete] = useState<AdditionalCost | null>(null);
  const rowRevisions = useRef(new Map<string, number>());
  const gridTemplateColumns = columns.map((column) => `${column.width}px`).join(" ");
  const clientsById = useMemo(() => new Map(clients.map((client) => [client.id, client])), [clients]);
  const load = useCallback(async () => { setLoading(true); try { const response = await fetch("/api/additional-costs"); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Could not load Additional Costs."); setRows(result.rows ?? []); setError(null); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : "Could not load Additional Costs."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const resize = (index: number, startX: number, startWidth: number) => { const onMove = (event: PointerEvent) => setColumns((current) => current.map((column, columnIndex) => columnIndex === index ? { ...column, width: Math.max(72, startWidth + event.clientX - startX) } : column)); const onUp = () => { window.removeEventListener("pointermove", onMove); window.removeEventListener("pointerup", onUp); }; window.addEventListener("pointermove", onMove); window.addEventListener("pointerup", onUp); };
  const update = useCallback(async (id: string, values: Record<string, unknown>) => { const previous = rows.find((row) => row.id === id); if (!previous) return; const revision = (rowRevisions.current.get(id) ?? 0) + 1; rowRevisions.current.set(id, revision); const rollback = Object.fromEntries(Object.keys(values).map((field) => [field, previous[field as keyof AdditionalCost]])); setRows((current) => current.map((row) => row.id === id ? { ...row, ...values } : row)); try { const response = await fetch("/api/additional-costs", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, values }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Could not save the change."); /* Keep the newest optimistic row: an older PATCH response contains an older row snapshot. */ } catch (updateError) { if (rowRevisions.current.get(id) === revision) setRows((current) => current.map((row) => row.id === id ? { ...row, ...rollback } : row)); toast.error("Additional cost could not be saved", { description: updateError instanceof Error ? updateError.message : "Please try again." }); } }, [rows]);
  const create = async (clientId: string) => { setCreatingFor(clientId); try { const response = await fetch("/api/additional-costs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ clientId }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Could not create the additional cost."); setRows((current) => [result.row, ...current]); setPickerOpen(false); setPickerQuery(""); toast.success("Additional cost added"); } catch (createError) { toast.error("Additional cost could not be created", { description: createError instanceof Error ? createError.message : "Please try again." }); } finally { setCreatingFor(null); } };
  const canDelete = (row: AdditionalCost) => { const role = String(currentUserRole ?? "").toLowerCase(); return ["admin", "director"].includes(role) || (!!currentUserId && ((clientAssignees[row.client_id] ?? []).includes(currentUserId) || (clientPmAssignees[row.client_id] ?? []).includes(currentUserId))); };
  const remove = async (row: AdditionalCost) => { setDeletingId(row.id); try { const response = await fetch(`/api/additional-costs?id=${encodeURIComponent(row.id)}`, { method: "DELETE" }); const result = await response.json(); if (!response.ok) throw new Error(result.error ?? "Could not delete the additional cost."); setRows((current) => current.filter((candidate) => candidate.id !== row.id)); setPendingDelete(null); toast.success("Additional cost deleted"); } catch (deleteError) { toast.error("Additional cost could not be deleted", { description: deleteError instanceof Error ? deleteError.message : "Please try again." }); } finally { setDeletingId(null); } };
  const filteredClients = clients.filter((client) => clientLabel(client).toLowerCase().includes(pickerQuery.trim().toLowerCase()));
  const clientSections = useMemo(() => { const sections = [...groups].sort((first, second) => first.sort_order - second.sort_order).map((group) => ({ id: group.id, label: group.name, clients: filteredClients.filter((client) => client.groupId === group.id) })).filter((section) => section.clients.length); const ungrouped = filteredClients.filter((client) => !client.groupId || !groups.some((group) => group.id === client.groupId)); if (ungrouped.length) sections.push({ id: "ungrouped", label: "Ungrouped", clients: ungrouped }); return sections; }, [filteredClients, groups]);
  const cell = (content: React.ReactNode, key: string) => <div key={key} className="min-w-0 border-b border-r border-slate-200">{content}</div>;
  return <section className="crm-board min-h-full bg-slate-50 p-4 sm:p-6">
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-semibold text-slate-800">Additional Costs (Lalamove/Defect/Replacement)</h1><p className="mt-1 text-sm text-slate-500">Log costs related to a CRM client. Each record remains linked to its selected project.</p></div><button onClick={() => setPickerOpen(true)} className="inline-flex items-center gap-2 rounded-md bg-[#16a5c4] px-3 py-2 text-sm font-semibold text-white hover:bg-[#118ca7]"><Plus size={16} /> Add additional cost</button></div>
    <div className="w-max min-w-full rounded-lg border border-slate-200 bg-white shadow-sm"><div><div className="grid bg-slate-50 text-xs font-semibold text-slate-500" style={{ gridTemplateColumns }}>{columns.map((column, index) => <div key={column.key} className="relative h-11 whitespace-nowrap border-b border-r border-slate-200 px-2 leading-[44px]">{column.label}<button aria-label={`Resize ${column.label || "actions"} column`} onPointerDown={(event) => { event.preventDefault(); resize(index, event.clientX, column.width); }} className="absolute -right-1 top-0 z-10 h-full w-2 cursor-col-resize" /></div>)}</div>
      {loading ? <div className="px-3 py-10 text-center text-sm text-slate-400">Loading Additional Costs…</div> : null}{!loading && !rows.length ? <div className="px-3 py-10 text-center text-sm text-slate-400">No additional costs yet. Add one by choosing a client.</div> : null}
      {rows.map((row) => { const client = clientsById.get(row.client_id); return <div key={row.id} className="grid hover:bg-slate-50" style={{ gridTemplateColumns }}>
        {cell(<div className="flex h-10 items-center truncate px-2 text-sm font-medium text-slate-700">{client ? clientLabel(client) : "Deleted client"}</div>, "project")}{cell(<input type="date" value={row.date_sent ?? ""} onChange={(event) => void update(row.id, { date_sent: event.target.value || null })} className={`${cellClass} w-full`} />, "date_sent")}{cell(<select value={row.people_id ?? ""} onChange={(event) => void update(row.id, { people_id: event.target.value || null })} className={`${cellClass} w-full`}><option value="">—</option>{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.full_name || profile.email || "Unnamed user"}</option>)}</select>, "people")}{cell(<input inputMode="decimal" value={row.cost ?? ""} onBlur={(event) => void update(row.id, { cost: event.target.value === "" ? null : event.target.value })} onChange={(event) => setRows((current) => current.map((candidate) => candidate.id === row.id ? { ...candidate, cost: event.target.value === "" ? null : Number(event.target.value) } : candidate))} className={`${cellClass} w-full text-right`} />, "cost")}{cell(<input defaultValue={row.remarks} onBlur={(event) => event.target.value !== row.remarks && void update(row.id, { remarks: event.target.value })} className={`${cellClass} w-full`} />, "remarks")}{cell(<input defaultValue={row.status} onBlur={(event) => event.target.value !== row.status && void update(row.id, { status: event.target.value })} className={`${cellClass} w-full`} />, "status")}
        {(["reason", "courier", "trip_id", "items_sent", "qty"] as const).map((field) => cell(<input defaultValue={row[field]} onBlur={(event) => event.target.value !== row[field] && void update(row.id, { [field]: event.target.value })} className={`${cellClass} w-full`} />, field))}{cell(<div className="flex h-10 items-center whitespace-nowrap px-2 text-xs text-slate-500">{new Date(row.created_at).toLocaleDateString("en-SG")}</div>, "created")}{(["verified", "discussed"] as const).map((field) => cell(<button aria-label={field} onClick={() => void update(row.id, { [field]: !row[field] })} className="mx-auto flex h-10 w-full items-center justify-center"><span className={`flex h-5 w-5 items-center justify-center rounded border ${row[field] ? "border-emerald-500 bg-emerald-500 text-white" : "border-slate-300 bg-white text-transparent"}`}><Check size={13} /></span></button>, field))}{cell(<button disabled={deletingId === row.id || !canDelete(row)} title={canDelete(row) ? "Delete additional cost" : "Only users assigned to this client can delete it"} onClick={() => setPendingDelete(row)} className="flex h-10 w-full items-center justify-center text-slate-400 hover:bg-red-50 hover:text-red-600 disabled:cursor-not-allowed disabled:opacity-30" aria-label="Delete additional cost"><Trash2 size={15} /></button>, "actions")}
      </div>; })}</div></div>{error ? <p className="m-3 text-sm text-red-600">{error}</p> : null}
    {pickerOpen ? <div className="fixed inset-0 z-[300] flex items-center justify-center bg-slate-950/35 p-4" role="dialog" aria-modal="true"><div className="flex max-h-[min(40rem,calc(100vh-2rem))] w-full max-w-xl flex-col overflow-hidden rounded-xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h2 className="font-semibold text-slate-800">Choose a client</h2><p className="mt-0.5 text-sm text-slate-500">The client becomes this record’s Project Name.</p></div><button onClick={() => setPickerOpen(false)} className="rounded p-1 text-slate-400 hover:bg-slate-100"><X size={19} /></button></div><label className="relative m-4 block"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input autoFocus value={pickerQuery} onChange={(event) => setPickerQuery(event.target.value)} placeholder="Search client name or Client ID…" className="w-full rounded-md border border-slate-300 py-2 pl-9 pr-3 text-sm outline-none focus:border-sky-500" /></label><div className="min-h-0 overflow-y-auto border-t border-slate-100 px-2 pb-2">{clientSections.map((section) => <div key={section.id}><div className="sticky top-0 border-y border-slate-100 bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-500">{section.label}</div>{section.clients.map((client) => <button key={client.id} disabled={creatingFor !== null} onClick={() => void create(client.id)} className="flex w-full items-center justify-between rounded-md px-3 py-3 text-left text-sm hover:bg-sky-50 disabled:opacity-50"><span className="font-medium text-slate-700">{client.name || "Unnamed client"}<span className="ml-2 font-mono text-xs text-slate-400">{client.displayId}</span></span>{creatingFor === client.id ? <span className="text-xs text-slate-400">Creating…</span> : <ChevronDown size={16} className="-rotate-90 text-slate-400" />}</button>)}</div>)}{!clientSections.length ? <p className="px-3 py-8 text-center text-sm text-slate-400">No matching clients.</p> : null}</div></div></div> : null}
    <AlertDialog open={Boolean(pendingDelete)} onOpenChange={(open) => !open && setPendingDelete(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete additional cost?</AlertDialogTitle><AlertDialogDescription>This additional-cost record will be permanently deleted. This action cannot be undone.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={Boolean(deletingId)}>Cancel</AlertDialogCancel><AlertDialogAction disabled={Boolean(deletingId)} onClick={(event) => { event.preventDefault(); if (pendingDelete) void remove(pendingDelete); }} className="bg-red-600 hover:bg-red-700">{deletingId ? "Deleting…" : "Delete"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </section>;
}
