"use client";

import { useState } from "react";
import { Bot, LockKeyhole, X } from "lucide-react";
import { useEscapeClose } from "./hooks/use-escape-close";

type ReferenceItem = {
  title: string;
  trigger: string;
  behaviour: string;
  scope?: string;
  source: string;
};

const automations: ReferenceItem[] = [
  { title: "Inbound lead ingestion and round-robin assignment", trigger: "A valid WordPress, WooCommerce, email-enquiry, or Make webhook arrives.", behaviour: "Creates or updates the lead and subitems, assigns the next eligible sales/director user through round robin, writes an activity entry, creates an in-app notification, and queues a Make event.", scope: "Webhook payloads are deduplicated by external ingestion identifiers.", source: "lib/inbound-leads.ts; app/api/inbound/*" },
  { title: "Non-enquiry email triage", trigger: "An inbound email is marked NON-ENQUIRY.", behaviour: "Stores the message in the Email Review queue instead of creating a CRM lead.", source: "app/api/inbound/email-enquiry/route.ts" },
  { title: "Waiting-lead reassignment", trigger: "Daily Vercel Cron at 16:00 UTC (midnight Singapore time).", behaviour: "Reassigns a lead that remains in Waiting beyond the response window to the next eligible assignee, records the activity, notifies the previous and new assignees, and queues a Make event.", scope: "The response window honours Singapore weekends, public holidays, and recorded company closures.", source: "app/api/cron/client-reply-automation/route.ts" },
  { title: "Follow Up date", trigger: "A new inbound lead is created.", behaviour: "Sets Follow Up to the third Singapore working day after creation.", scope: "Working days exclude weekends and entries in the Working Calendar.", source: "lib/inbound-leads.ts; lib/working-calendar.ts" },
  { title: "QuickBooks estimate invoice sync", trigger: "Daily Vercel Cron at 18:00 UTC (02:00 Singapore time).", behaviour: "Finds QuickBooks invoices linked to tracked estimates and updates invoice number, date, tax, total, balance, and tracking fields in CRM.", source: "app/api/cron/quickbooks-invoice-sync/route.ts" },
  { title: "QuickBooks Bill sync", trigger: "Daily Vercel Cron at 18:10 UTC (02:10 Singapore time).", behaviour: "Refreshes stored bill cost, supplier, and invoice number. If the linked Bill cannot be fetched, marks it ERROR – Could not find Bill.", source: "app/api/cron/quickbooks-bill-sync/route.ts" },
  { title: "Official Singapore holiday refresh", trigger: "Manual Refresh official holidays action, plus annual Vercel Cron on 1 October at 18:00 UTC.", behaviour: "Imports/upserts MOM/data.gov.sg public holidays while preserving manually created closures or overrides on the same date.", source: "app/api/working-calendar/sync/route.ts; app/api/cron/working-calendar-sync/route.ts" },
  { title: "CRM Bin retention purge", trigger: "Daily Vercel Cron at 17:00 UTC (01:00 Singapore time).", behaviour: "Permanently removes soft-deleted clients/subitems older than 30 days, their stored files, and writes a purge audit entry.", source: "app/api/cron/crm-bin-purge/route.ts" },
  { title: "Make integration outbox", trigger: "Authenticated Make/cron call to the outbox route.", behaviour: "Retries and dispatches durable queued lead-assignment/reassignment events to Make without rolling back the CRM action when Make is unavailable.", source: "app/api/cron/make-outbox/route.ts; lib/make-integration.ts" },
  { title: "Payment voucher bill cost propagation", trigger: "A QuickBooks Bill is created, linked, edited, or refreshed.", behaviour: "Sets the voucher Cost to the sum of its expense-line amounts and updates its linked subitem cost where applicable.", source: "app/api/quickbooks/generate-bill*.ts; app/api/cron/quickbooks-bill-sync/route.ts" },
  { title: "QuickBooks Bill document extraction", trigger: "A user uploads one document for Bill pre-filling.", behaviour: "Calls Azure Document Intelligence, extracts invoice fields/lines with confidence metadata, pre-fills the Bill draft, and retains the original file as a Bill attachment.", scope: "Extraction failure leaves the file uploaded and available in the document pane for manual entry.", source: "app/api/quickbooks/extract-bill-document/route.ts" },
  { title: "QuickBooks attachment delivery", trigger: "A Bill is created or updated with attachments.", behaviour: "Uploads the selected attachment files to the corresponding QuickBooks Bill after the Bill is created.", source: "app/api/quickbooks/generate-bill*.ts; app/api/quickbooks/bill/route.ts" },
  { title: "Status-to-group movement", trigger: "A CRM lead status is changed to a mapped status, including Closed.", behaviour: "Moves the client into the matching CRM group automatically. Closing also ensures the current Closed Leads group exists; the board presents an Undo action for the automatic move.", source: "components/CRMBoard.tsx; app/api/crm-groups/ensure-current-closed/route.ts" },
  { title: "Overdue timeline progress", trigger: "An editable Subitem detail view opens.", behaviour: "Marks timeline rows as Late when their end date has passed and they are not already complete, delivered, shipped out, or Late.", source: "components/SubitemDetailView.tsx" },
  { title: "Shipment auto-lock", trigger: "A shipment reaches its configured auto-lock time while the shipment grid is open.", behaviour: "Applies the shipment’s due auto-lock and refreshes the row state. The API also validates the applicable lock requirements.", source: "app/(protected)/app/shipper/ShipmentGrid.tsx; app/api/shipper/shipments/route.ts" },
  { title: "System label resolution", trigger: "A process applies a protected system label or evaluates a label condition.", behaviour: "Resolves the label by stable option ID/system key rather than its visible name, so renaming a label does not break the process.", source: "lib/system-labels.ts; label option APIs and migrations" },
];

const restrictions: ReferenceItem[] = [
  { title: "Administration and account management", trigger: "Admin screens and account APIs.", behaviour: "Only directors and developers can invite users, manage users, or suspend accounts. Director accounts cannot be suspended.", source: "app/api/admin/users/route.ts; app/api/admin/invites/route.ts" },
  { title: "OCF configuration", trigger: "Top-bar Settings → OCF Configuration.", behaviour: "Visible and editable only to directors and developers.", source: "components/TopBar.tsx; components/OcfConfigurationSettingsModal.tsx" },
  { title: "This reference", trigger: "Top-bar Settings → Automations & Permission Restrictions.", behaviour: "Visible to directors and developers; read-only by design.", source: "components/TopBar.tsx" },
  { title: "Working Calendar", trigger: "Sidebar Calendar and calendar APIs.", behaviour: "Only admin, director, and dev users can view/manage the Working Calendar. Official MOM/data.gov.sg entries cannot be deleted; manual dates require confirmation.", source: "components/Sidebar.tsx; app/api/working-calendar/*" },
  { title: "CRM client editing", trigger: "CRM Board rows and update APIs.", behaviour: "Sales and PM users can edit assigned clients; admins/directors can edit regardless of assignment. Other row actions are separately guarded.", source: "components/ui/clientrows.tsx; CRM Board update flows" },
  { title: "Subitem lock", trigger: "A client’s subitems are locked.", behaviour: "Prevents protected subitem/payment-voucher changes. Only directors and developers can toggle the lock.", source: "components/CRMBoard.tsx; components/ui/subitems.tsx; app/api/additional-costs/route.ts" },
  { title: "CRM groups and custom columns", trigger: "CRM Board configuration actions.", behaviour: "Admins, directors, and developers can create groups. Only directors and developers can create/manage custom columns.", source: "components/CRMBoard.tsx" },
  { title: "Labels/options", trigger: "Label management and option APIs.", behaviour: "Admin, director, and dev users can manage protected option layouts. A label used by an automation cannot be deleted until its dependency is resolved.", source: "app/api/options/delete/route.ts; app/api/options/reorder/route.ts" },
  { title: "Customer profiles and blacklist", trigger: "Customer Profiles actions.", behaviour: "Only directors/developers can change blacklist status. Admins, directors, and developers can delete customer profiles. Authors may delete their own remarks; privileged users can delete any.", source: "app/api/customer-profiles/route.ts; app/api/customer-profiles/remarks/route.ts" },
  { title: "CRM Bin permanent deletion", trigger: "Permanent delete from the Bin.", behaviour: "The creator may permanently delete their item within 72 hours; directors/developers may do so at any time.", source: "app/api/crm-bin/permanent-delete/route.ts" },
  { title: "Payment Voucher board", trigger: "Payment voucher access and row actions.", behaviour: "Internal roles can access the board. Deleting/recovering standard vouchers is limited to admins/directors; QuickBooks-Bills-only rows additionally permit dev users. Bill-related columns are read-only pending a dedicated editor.", source: "app/api/additional-costs/route.ts; components/AdditionalCostsBoard.tsx" },
  { title: "QuickBooks Bills only", trigger: "Third Payment Voucher group.", behaviour: "The standalone QuickBooks Bill workspace is visible only to admin, director, and dev users; creating QuickBooks-only Bills uses the same role set.", source: "components/AdditionalCostsBoard.tsx; app/api/quickbooks/generate-bill-only/route.ts" },
  { title: "QuickBooks estimate and bill actions", trigger: "QuickBooks create/update routes.", behaviour: "Internal staff can use supported QuickBooks actions; estimate updates additionally require assignment unless the user is admin/director/dev. Some destructive voucher/bill operations remain admin/director-only.", source: "app/api/quickbooks/estimate-update/route.ts; app/api/quickbooks/generate-bill/route.ts" },
  { title: "Email Review", trigger: "Email Review page and API.", behaviour: "Review and decisions are read-only/limited to admin, director, and dev users.", source: "components/EmailReviewPanel.tsx; app/api/email-review/route.ts" },
  { title: "Round Robin", trigger: "Round Robin panel and API.", behaviour: "Admins, directors, and developers can manage the assignment queue; eligible assignees are sales and director users according to the queue rules.", source: "components/RoundRobinPanel.tsx; app/api/round-robin/route.ts" },
  { title: "Shipper operations", trigger: "Shipper pages and APIs.", behaviour: "PM, admin, director, and dev users can access shipment staging, pushes, files, and history. Director-only controls remain protected within the shipper workflow.", source: "app/api/shipper/*" },
  { title: "Cron and webhook endpoints", trigger: "Background jobs and external integrations.", behaviour: "Cron endpoints require CRON_SECRET; Make routes also accept MAKE_INTEGRATION_SECRET where configured; inbound webhooks require their dedicated integration secrets and enforce payload limits.", source: "app/api/cron/*; app/api/inbound/*" },
];

export default function AutomationsPermissionsModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [tab, setTab] = useState<"automations" | "restrictions">("automations");
  useEscapeClose({ open, onClose });
  if (!open) return null;
  const items = tab === "automations" ? automations : restrictions;
  return <div className="fixed inset-0 z-[90] flex items-center justify-center bg-black/40 px-4"><div className="flex max-h-[calc(100vh-2rem)] w-full max-w-5xl flex-col overflow-hidden rounded-xl bg-white shadow-2xl"><div className="flex shrink-0 items-start justify-between border-b border-slate-200 px-5 py-4"><div><h2 className="text-base font-semibold text-slate-900">Automations & Permission Restrictions</h2><p className="mt-1 text-xs text-slate-500">Read-only reference of the current coded behaviour. Entries include their implementation source for future review.</p></div><button type="button" onClick={onClose} className="rounded p-1 text-slate-500 hover:bg-slate-100" aria-label="Close"><X size={18} /></button></div><div className="shrink-0 border-b border-slate-200 px-5 pt-3"><div className="flex gap-2"><button type="button" onClick={() => setTab("automations")} className={`inline-flex items-center gap-2 border-b-2 px-3 py-2 text-sm font-medium ${tab === "automations" ? "border-sky-600 text-sky-700" : "border-transparent text-slate-500 hover:text-slate-800"}`}><Bot size={16} />Automations ({automations.length})</button><button type="button" onClick={() => setTab("restrictions")} className={`inline-flex items-center gap-2 border-b-2 px-3 py-2 text-sm font-medium ${tab === "restrictions" ? "border-sky-600 text-sky-700" : "border-transparent text-slate-500 hover:text-slate-800"}`}><LockKeyhole size={16} />Permission restrictions ({restrictions.length})</button></div></div><div className="min-h-0 flex-1 overflow-y-auto bg-slate-50 p-5"><div className="space-y-3">{items.map((item) => <article key={item.title} className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1"><h3 className="font-semibold text-slate-800">{item.title}</h3><code className="text-[11px] text-slate-400">{item.source}</code></div><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-[130px_1fr]"><dt className="font-medium text-slate-500">Trigger / scope</dt><dd className="text-slate-700">{item.trigger}</dd><dt className="font-medium text-slate-500">Current behaviour</dt><dd className="text-slate-700">{item.behaviour}</dd>{item.scope ? <><dt className="font-medium text-slate-500">Notes</dt><dd className="text-slate-700">{item.scope}</dd></> : null}</dl></article>)}</div></div><div className="flex shrink-0 justify-end border-t border-slate-200 px-5 py-3"><button type="button" onClick={onClose} className="rounded-md border border-slate-300 px-4 py-2 text-sm text-slate-700 hover:bg-slate-50">Close</button></div></div></div>;
}
